---
- name: list
  hosts: all
  become: true
  vars:
      packages:
       # - fusioninventory-agent
        - git
      state: latest
  tasks:
    - name: Install applications now
      ansible.builtin.apt:
       name: "{{ packages }}"
       state: present
       update_cache: yes


  tasks:
    - name: Lade neueste agent.cfg herunter
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/gsg-git/awx_pub/main/linux_playbooks/fusion_inventory/agent.cfg" #raw. is VERY IMPORTANT!!!
        dest: "/tmp/agent.cfg"
        owner: root
        group: root
        mode: '0644'

  tasks:
    - name: copy
      become: true
      ansible.builtin.copy:
        src: /tmp/agent.cfg
        dest: /etc/fusioninventory/agent.cfg
        owner: root
        group: root
        mode: '0644'
        remote_src: true
        force: yes


    - name: fusioninv service reboot
      service:
        name: fusioninventory-agent
        state: restarted


