---
- name: FusionInventory Agent Konfiguration aktualisieren
  hosts: all
  become: yes  # Benötigt sudo-Berechtigungen

  tasks:
    - name: Lade neueste agent.cfg herunter
      get_url:
        url: https://github.com/gsg-git/awx_pub/blob/main/linux_playbooks/fusion_inventory/agent.cfg
        dest: "/tmp/agent.cfg"
        mode: '0644'
