---
- name: list
  hosts: all
  become: true
  vars:
      packages:
       # - fusioninventory-agent
        - git
      state: latest
  tasks:
    - name: Install applications now
      ansible.builtin.apt:
       name: "{{ packages }}"
       state: present
       update_cache: yes

- name: Set values for config
  hosts: all
  gather_facts: false
  vars:
    fusioninventory__agent_conf_src: '/tmp/agent.cfg'
    configpath: '/etc/fusioninventory/agent.cfg'
  
  tasks:
    - name: Lade neueste agent.cfg herunter
      get_url:
        url: https://github.com/gsg-git/awx_pub/blob/main/linux_playbooks/fusion_inventory/agent.cfg
        dest: "/tmp/agent.cfg"
        mode: '0644'

      tasks:
    - name: copyconfig
      copy:
        src: "{{ fusioninventory__agent_conf_src }}"
        dest: "{{ configpath }}"
        owner: root
        group: root
        mode: '0644'
    - name: fusioninv service reboot
      service:
        name: fusioninventory-agent
        state: restarted


