---
- name: copy
  become: yes
  become_user: root
  become_method: sudo
  become_flags: '-i'
  hosts: all
  gather_facts: no
  tasks:
    - name: copy
      ansible.builtin.copy:
        src: /home/agent.cfg
        dest: /home/test/agent.cfg
        owner: root
        group: root
        mode: '0644'
      delegate_to: localhost
      become: true