---
- name: SSH Connection Test
  hosts: all
  gather_facts: no

  tasks:
  - name: SSH Connection Test
    ansible.builtin.ping:

  - name: Ausgabe, wenn der Host erreichbar ist
    debug:
      msg: "Der Host {{ inventory_hostname }} ist erreichbar."
