- name:  ========== Export AWX Settings ==========
  connection: local
  hosts: localhost
  gather_facts: no

  environment:
   CONTROLLER_USERNAME: "{{ vault_controller_username }}"
   CONTROLLER_PASSWORD: "{{ vault_controller_password }}"
   CONTROLLER_HOST: "{{ awx_url }}"
  
  tasks:
    - name: Export All Settings
      awx.awx.export:
        all: True
      register: assets

    - name: SAVE EXPORT TO YML FILE
      delegate_to: localhost
      copy:
        dest: "/var/lib/awx/exports/backup.yml"
        content: "{{ assets.assets | to_yaml }}"

    - name: SAVE JOB_TEMPLATES TO YML FILE
      delegate_to: localhost
      copy:
        dest: "/var/lib/awx/exports/backup_{{ item.key }}.yml"
        content: "{{ { item.key : item.value } | to_yaml }}"
      with_items: "{{ assets.assets | dict2items }}"