---
- name: Writing Web Server 
  hosts: any
  remote_user: root
  become: yes

  tasks:
  - name: Firewall Rule
    firewalld:
      zone: public
      service: smtp
      permanent: yes
      state: enabled

  - name: Reload Firewalld rules
    service:
      name: firewalld
      state: restarted