---
- hosts: all
  become: true
  vars:
      packages:
        - vim
        - unzip
        - zip
        - wget
        - git
      state: latest
  tasks:
    - name: Angegebene Pakete installieren
      ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
...



